apiVersion: 1
contactPoints:
  - orgId: 1
    name: telegram-monitoring
    receivers:
      - uid: telegram-monitoring-1
        type: telegram
        settings:
          bottoken: $__env{TELEGRAM_BOT_TOKEN}
          chatid: $__env{TELEGRAM_MONITORING_CHAT_ID}
          message: |
            {{ template "default.message" . }}
